services:
  skillsphere_app:
    container_name: skillsphere_app
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - shared_data:/shared_data
    depends_on:
      - skillsphere_database
    env_file:
      - ./.env
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /backend"
    networks:
      - production
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - shared_data:/shared_data 
    depends_on:
      - skillsphere_app
    networks:
      - production
  skillsphere_database:
    image: postgres:16
    container_name: skillsphere_database
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    networks:
      - production
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - skillsphere_app
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - shared_data:/shared_data 
    networks:
      - production
  # test_database:
  #   image: postgres:latest
  #   container_name: test_database
  #   environment:
  #     - POSTGRES_DB=skillsphere_test_db
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=1234
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_test_database:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - skillsphere_database
    #  - test_database
    networks:
      - production
  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - production

networks:
  production:

volumes:
  postgres_database:
  shared_data: 
  # postgres_test_database:
