FROM node:16-alpine

WORKDIR /frontend

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend /frontend

RUN npm run build

RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3000"]

