events {}

http {
    upstream frontend {
        server skillsphere-frontend-1:3000;  
    }

    upstream backend {
        server skillsphere_app:8000;  # Прокси на порт 8000 бэкенда
    }

    server {
        listen 80;
        server_name hqua0348217.online-vm.com;

        # Обработка статичных файлов
        location /shared_data/ {
            alias /shared_data/;
        }

        # Прокси для всех путей, которые обслуживаются фронтендом
        location / {
            proxy_pass http://frontend/;  # Прокси запросов на фронтенд
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Прокси для API, который обслуживается на порту 8000
        location /api/ {
            proxy_pass http://backend/;  # Прокси на бэкенд
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
