events {}

http {
    # upstream frontend {
    #     server frontend:3000;  
    # }

    # upstream backend {
    #     server skillsphere_app:8000;

    # }

    server {
        listen 80;
        server_name 185.126.115.49;

        location /shared_data/ {
            alias /shared_data/;  
        }

        location / {
            proxy_pass http://frontend:3000/;
        }

        location /api/ {
            proxy_pass http://skillsphere_app:8000/;
        }


    }
}
