"""New migration

Revision ID: 6807b8d103f8
Revises: 0bf7964da328
Create Date: 2024-09-06 10:45:38.330292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6807b8d103f8"
down_revision: Union[str, None] = "0bf7964da328"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course",
        sa.Column(
            "is_published", sa.Boolean(), server_default="false", nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "identity_role",
            sa.Enum("USER", "ADMIN", "GUEST", name="role"),
            nullable=False,
        ),
    )
    op.drop_column("user", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "role",
            postgresql.ENUM("TEACHER", "USER", "ADMIN", "GUEST", name="role"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user", "identity_role")
    op.drop_column("course", "is_published")
    # ### end Alembic commands ###
