"""Migration

Revision ID: 96e3b2aad986
Revises: 8f4966f20cac
Create Date: 2024-09-10 07:03:15.756849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96e3b2aad986"
down_revision: Union[str, None] = "8f4966f20cac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("video_url", sa.String(), nullable=False)
    )
    op.add_column(
        "course", sa.Column("photo_url", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "photo_url")
    op.drop_column("course", "video_url")
    # ### end Alembic commands ###
