"""migration

Revision ID: 5db26df3987a
Revises: 96e3b2aad986
Create Date: 2024-09-11 09:54:22.261235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5db26df3987a"
down_revision: Union[str, None] = "96e3b2aad986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course", "video_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "course", "photo_url", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course", "photo_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "course", "video_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
