"""migration

Revision ID: d0d7a4a9f6a4
Revises: d002f35675ef
Create Date: 2024-09-19 06:02:33.927182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0d7a4a9f6a4"
down_revision: Union[str, None] = "d002f35675ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_students",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(
        "idx_unique_user_first_last_names",
        "user",
        ["username", "first_name", "last_name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "idx_unique_user_first_last_names", "user", type_="unique"
    )
    op.drop_table("course_students")
    # ### end Alembic commands ###
