"""Migration

Revision ID: 8f4966f20cac
Revises: 8cc68148fa8c
Create Date: 2024-09-09 09:22:09.959392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f4966f20cac"
down_revision: Union[str, None] = "8cc68148fa8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "module", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "module", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
