"""New table ContactUs

Revision ID: 419f394eb355
Revises: 5db26df3987a
Create Date: 2024-09-11 11:38:35.596585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "419f394eb355"
down_revision: Union[str, None] = "5db26df3987a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contactus",
        sa.Column("full_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("message", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_checked", sa.Boolean(), server_default="false", nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contactus")
    # ### end Alembic commands ###
