"""migration

Revision ID: 81f951a322eb
Revises: d5d839b697d1
Create Date: 2024-10-15 19:03:35.709797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81f951a322eb"
down_revision: Union[str, None] = "d5d839b697d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test",
        sa.Column(
            "count_correct_answers",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test", "count_correct_answers")
    # ### end Alembic commands ###
