"""Migration

Revision ID: 0bf7964da328
Revises: ac042256d24e
Create Date: 2024-09-05 17:57:01.275083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bf7964da328"
down_revision: Union[str, None] = "ac042256d24e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course_instructors",
        sa.Column("course_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "course_instructors",
        sa.Column("instructor_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None, "course_instructors", "user", ["instructor_id"], ["id"]
    )
    op.create_foreign_key(
        None, "course_instructors", "course", ["course_id"], ["id"]
    )
    op.drop_constraint("user_first_name_last_name_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "user_first_name_last_name_key", "user", ["first_name", "last_name"]
    )
    op.drop_constraint(None, "course_instructors", type_="foreignkey")
    op.drop_constraint(None, "course_instructors", type_="foreignkey")
    op.drop_column("course_instructors", "instructor_id")
    op.drop_column("course_instructors", "course_id")
    # ### end Alembic commands ###
