"""migration

Revision ID: 0dea88d050d6
Revises: 9c0de94335db
Create Date: 2024-10-15 16:03:56.389846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dea88d050d6"
down_revision: Union[str, None] = "9c0de94335db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "step",
        sa.Column("video_path", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test",
        sa.Column(
            "count_correct_answers",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["step.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_id"),
    )
    op.create_table(
        "answer",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "is_correct", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer")
    op.drop_table("test")
    op.drop_table("step")
    # ### end Alembic commands ###
