"""migration

Revision ID: e7621bbc0867
Revises: 0dea88d050d6
Create Date: 2024-10-15 17:07:52.948267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7621bbc0867"
down_revision: Union[str, None] = "0dea88d050d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("step", sa.Column("lesson_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "step", "lesson", ["lesson_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "step", type_="foreignkey")
    op.drop_column("step", "lesson_id")
    # ### end Alembic commands ###
