"""migration

Revision ID: da267e0cef84
Revises: 973b71f25d0f
Create Date: 2024-10-14 07:26:24.369626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da267e0cef84"
down_revision: Union[str, None] = "973b71f25d0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "comment", "course", ["course_id"], ["id"])
    op.add_column("course", sa.Column("video_url", sa.String(), nullable=True))
    op.add_column("course", sa.Column("photo_url", sa.String(), nullable=True))
    op.add_column(
        "course",
        sa.Column(
            "is_published", sa.Boolean(), server_default="false", nullable=True
        ),
    )
    op.create_foreign_key(
        None, "course_instructors", "course", ["course_id"], ["id"]
    )
    op.create_foreign_key(
        None, "course_students", "course", ["course_id"], ["id"]
    )
    op.create_foreign_key(None, "module", "course", ["course_id"], ["id"])
    op.create_foreign_key(None, "payment", "course", ["course_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_constraint(None, "module", type_="foreignkey")
    op.drop_constraint(None, "course_students", type_="foreignkey")
    op.drop_constraint(None, "course_instructors", type_="foreignkey")
    op.drop_column("course", "is_published")
    op.drop_column("course", "photo_url")
    op.drop_column("course", "video_url")
    op.drop_constraint(None, "comment", type_="foreignkey")
    # ### end Alembic commands ###
