"""migration

Revision ID: d5d839b697d1
Revises: e7621bbc0867
Create Date: 2024-10-15 19:03:08.598482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5d839b697d1"
down_revision: Union[str, None] = "e7621bbc0867"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test", "count_correct_answers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test",
        sa.Column(
            "count_correct_answers",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
