"""MIGRATION

Revision ID: 8b208766e7bd
Revises: 6807b8d103f8
Create Date: 2024-09-06 17:53:29.583737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b208766e7bd"
down_revision: Union[str, None] = "6807b8d103f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "admin", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.drop_column("user", "identity_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "identity_role",
            postgresql.ENUM("TEACHER", "USER", "ADMIN", "GUEST", name="role"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user", "admin")
    # ### end Alembic commands ###
